inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RescueStandardError:
  EnforcedStyle: implicit

Metrics/BlockLength:
  IgnoredMethods:
    - namespace
    - describe
    - context
  Max: 10

# Configuration parameters: CountComments, CountAsOne, IgnoredMethods.
Metrics/MethodLength:
  IgnoredMethods:
    - should_write?
    - generate_509_certificate
    - generate_root_ca
  Max: 11

Layout/LineLength:
  Max: 120

Lint/EmptyBlock:
  Exclude:
    - features/step_definitions/rails.rb
    - lib/dice_bag/tasks/config.rake

Lint/DuplicateBranch:
  Exclude:
    - lib/dice_bag/dice_bag_file.rb
