language: ruby
dist: bionic
cache: bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

before_install:
  - gem update --system -N > /dev/null && echo "Rubygems version $(gem --version)"
  - if [ $TRAVIS_RUBY_VERSION == 2.7 ]; then gem install rubocop:1.3.1; fi

script:
  - bundle exec rspec --format progress
  - bundle exec cucumber --format progress
  - if [ $TRAVIS_RUBY_VERSION == 2.7 ]; then rubocop; fi

deploy:
  provider: rubygems
  api_key:
    secure: OOaw+kt318CvvkzqnNO6FpbNUdlS4vDK+0LNLD4fgncZ1Lx+cIx3FmBnB3C8MYDWLGciw9qwZ/JnYIn7v9a5IWuC3Yeag+l7KgC5KTxn2j/11NfAPymow+r9RPgsAlkDiUkm7uSw7Se87JsA2l4PZIr5bDhjTKiYXwHL/gaHg2U=
  on:
    tags: true
    condition: "$TRAVIS_RUBY_VERSION == 2.7"
