language: ruby
rvm:
- 2.3.7
- 2.4.4
- 2.5.1
before_install:
- gem update bundler
script: bundle exec rspec && bundle exec cucumber
deploy:
  provider: rubygems
  api_key:
    secure: OOaw+kt318CvvkzqnNO6FpbNUdlS4vDK+0LNLD4fgncZ1Lx+cIx3FmBnB3C8MYDWLGciw9qwZ/JnYIn7v9a5IWuC3Yeag+l7KgC5KTxn2j/11NfAPymow+r9RPgsAlkDiUkm7uSw7Se87JsA2l4PZIr5bDhjTKiYXwHL/gaHg2U=
  on:
    tags: true
    condition: "$TRAVIS_RUBY_VERSION == 2.5.1"
